# Generated by Django 4.2.15 on 2024-08-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
