# Generated by Django 4.2.15 on 2024-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_alter_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email_active_code',
            field=models.CharField(default='', max_length=128),
        ),
    ]
