# Generated by Django 4.2.15 on 2024-09-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0006_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
