# Generated by Django 4.2.15 on 2024-09-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0007_commentmodel_is_best'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
