# Generated by Django 4.2.15 on 2024-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='selected_categories',
            field=models.ManyToManyField(to='product_module.productcategory'),
        ),
    ]
