# Generated by Django 4.2.15 on 2024-09-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
